if (!file.exists('UCI.zip')) {
  download.file('https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip',destfile='UCI.zip')
}
unzip('UCI.zip')
UCI=read.csv(file="household_power_consumption.txt",header = TRUE, sep=';')
require('dplyr')
UCI2=filter(UCI, UCI$Date == '1/2/2007'|UCI$Date == '2/2/2007',na.rm=TRUE)
UCI2$Date=as.Date(UCI2$Date, '%d/%m/%Y')
UCI2$Global_active_power=as.numeric(as.character(UCI2$Global_active_power))
UCI2$Global_reactive_power=as.numeric(as.character(UCI2$Global_reactive_power))
UCI2$Voltage=as.numeric(as.character(UCI2$Voltage))
UCI2$Global_intensity=as.numeric(as.character(UCI2$Global_intensity))
UCI2$Sub_metering_1=as.numeric(as.character(UCI2$Sub_metering_1))
UCI2$Sub_metering_2=as.numeric(as.character(UCI2$Sub_metering_2))
UCI2$Sub_metering_3=as.numeric(as.character(UCI2$Sub_metering_3))
datetime=paste(UCI2$Date,UCI2$Time)
UCI2$Date=strptime(datetime, "%Y-%m-%d %H:%M:%S")
UCI2$Date=as.POSIXct(UCI2$Date)
Sys.setlocale("LC_TIME","en_US.UTF-8")
png(filename = 'plot3.png', width = 480, height = 480, units = 'px')
with(UCI2, plot(Date,Sub_metering_1, type = "l",xlab='',ylab='Energy sub metering'))
lines(UCI2$Date, UCI2$Sub_metering_2, col = "red")
lines(UCI2$Date, UCI2$Sub_metering_3, col = "blue")
legend("topright", pch = "_", col=c("black","red","blue") , legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.off()